### ISSUE TITLE
MemoryAllocationError calling midiInOpen

### ISSUE THREAD

**Issue by jordaofranca** [C9Glax/OBSKorgNanokontrol2#14]
Stumbled into this issue while running it
```
Unhandled Exception: NAudio.MmException: MemoryAllocationError calling midiInOpen
   at NAudio.Midi.MidiIn..ctor(Int32 deviceNo)
   at MidiAccess.MidiInformation.GetInputDeviceWithName(String name)
   at MidiAccess.Controller..ctor(String inputDeviceName, String outputDeviceName)
   at nanoKontrol2OBS.Kontrol2OBS..ctor(String url, String password, LogEventHandler statusCallback, LogEventHandler warningCallback, LogEventHandler infoCallback)
   at ConsoleExecutable.Executable..ctor(String url, String password)
   at ConsoleExecutable.Executable.Main(String[] args)
```

**Comment by C9Glax** [comment]
Problem seems to originate from NAudio library.
https://github.com/naudio/NAudio
Seems like there is an issue with opening your MIDI-Device. Is more than 1 program trying to use it?
You need to download the KORG driver https://www.korg.com/us/support/download/product/0/159/ to be able to connect to KORG nanoKontrol2 with more than 1 program.

**Comment by jordaofranca** [comment]
I have fixed by resinstalling it thanks
