### ISSUE TITLE
Noob issue : OBSKorgNanokontrol2 crashing on start

### ISSUE THREAD

**Issue by vk3xxx** [C9Glax/OBSKorgNanokontrol2#2]
This may be a total noob issue but upon starting system I get following issue

[13:42:56.203] (Status) Loading Bindings...
[13:42:56.231] (Status) Connecting to websocket...
[13:42:56.301] (Status) Setting up audio (This might take a while)...

Unhandled Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at nanoKontrol2OBS.Kontrol2OBS.SetupAudio()
   at nanoKontrol2OBS.Kontrol2OBS.Create()
   at ConsoleExecutable.Executable..ctor(String url, String password)
   at ConsoleExecutable.Executable.Main(String[] args)

Can you please assist?

**Comment by C9Glax** [comment]
I already have an idea what is going on...
Would you be able to replace the .dll I attached and post the log from that as well?
[nanoKontrol2OBS.zip](https://github.com/C9Glax/OBSKorgNanokontrol2/files/4919767/nanoKontrol2OBS.zip)

**Comment by vk3xxx** [comment]
Looks like same issue mate.

[20:57:55.593] (Status) Loading Bindings...
[20:57:55.619] (Status) Connecting to websocket...
[20:57:55.691] (Status) Setting up audio (This might take a while)...

Unhandled Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at nanoKontrol2OBS.Kontrol2OBS.SetupAudio()
   at nanoKontrol2OBS.Kontrol2OBS.Create()
   at ConsoleExecutable.Executable..ctor(String url, String password)
   at ConsoleExecutable.Executable.Main(String[] args)

**Comment by C9Glax** [comment]
Okay, that is weird. I now added a bunch of debugging Console.WriteLines...
If you want to go ahead and replace that file for me again :)
[nanoKontrol2OBS.zip](https://github.com/C9Glax/OBSKorgNanokontrol2/files/4926836/nanoKontrol2OBS.zip)

There are only three arrays per-se in that method, so i am not sure anymore what is causing the issue...

**Comment by vk3xxx** [comment]
Similar output mate...

[12:35:16.191] (Status) Loading Bindings...
[12:35:16.225] (Status) Connecting to websocket...
[12:35:16.323] (Status) Setting up audio (This might take a while)...

Unhandled Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at nanoKontrol2OBS.Kontrol2OBS.SetupAudio()
   at nanoKontrol2OBS.Kontrol2OBS.Create()
   at ConsoleExecutable.Executable..ctor(String url, String password)
   at ConsoleExecutable.Executable.Main(String[] args)

**Comment by C9Glax** [comment]
Okay that is like literally not possible, because the first Line of that Method is:
`private void SetupAudio()
        {
            this.LogInfo("Test starting here:");`

**Comment by C9Glax** [comment]
You definitely replaced the old nanoKontrol2OBS.dll with the new one?

**Comment by vk3xxx** [comment]
Let me download again and make sure

**Comment by vk3xxx** [comment]
The file you have linked to is dated 10/06, can you share updated link?

**Comment by C9Glax** [comment]
[nanoKontrol2OBS.zip](https://github.com/C9Glax/OBSKorgNanokontrol2/files/4931655/nanoKontrol2OBS.zip)
Well that solves the issue... Had the old repo location

**Comment by vk3xxx** [comment]
much better...

[17:13:3.66] (Status) Loading Bindings...
[17:13:3.96] (Status) Connecting to websocket...
[17:13:3.170] (Status) Setting up audio (This might take a while)...
[17:13:3.173] (Info) Test starting here:
[17:13:3.179] (Info) SpecialSource-Name: Desktop Audio
[17:13:3.179] (Info) SpecialSource-Name:
[17:13:3.179] (Info) SpecialSource-Name: Yeti Mic
[17:13:3.180] (Info) SpecialSource-Name: Wireless Mic
[17:13:3.180] (Info) SpecialSource-Name:
[17:13:3.183] (Info) Connected: Wireless Mic
[17:13:3.183] (Info) Connected: Yeti Mic
[17:13:3.183] (Info) Connected: Desktop Audio
[17:13:3.210] (Info) PID Desktop Audio default

Unhandled Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at nanoKontrol2OBS.Kontrol2OBS.SetupAudio()
   at nanoKontrol2OBS.Kontrol2OBS.Create()
   at ConsoleExecutable.Executable..ctor(String url, String password)
   at ConsoleExecutable.Executable.Main(String[] args)

**Comment by C9Glax** [comment]
`[17:13:3.210] (Info) PID Desktop Audio default`
There we go, `default` should be a PID of an audio device, you do not have a specific source set as desktop-audio device correct?

**Comment by vk3xxx** [comment]
That fixed it.  It was set to Default in OBS, I changed it to the currently used Audio out.  I had it set to default so it would pick between VR headset output and my monitor speakers depending on what I was using.

Glad we found the problem.  Thanks for your efforts :)

**Comment by C9Glax** [comment]
Sure no problem, thanks for pointing out that this is a thing...
