### ISSUE TITLE
nanoKontrol2OBS.Kontrol2OBS.SetupNanoController(): System.NullReferenceException

### ISSUE THREAD

**Issue by C9Glax** [C9Glax/OBSKorgNanokontrol2#3]
From: [obsforum](https://obsproject.com/forum/threads/korg-nanokontrol2-obs-control.123196/#post-472086)

> first off thank you for working on this, the nanok2 just happens to be one of my old midi devices I still have and already was trying to use it through obs in various ways because I do stream often. However I'm having an issue with it. When it initially connects it gives the following error and then crashes.

```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
at nanoKontrol2OBS.Kontrol2OBS.SetupNanoController()
at nanoKontrol2OBS.Kontrol2OBS.Create()
at ConsoleExecutable.Executable..ctor(String url, String password)
at ConsoleExecutable.Executable.Main(String[] args)
```

**Comment by C9Glax** [comment]
So right off the bat I have some suspicions on what might be happening:
In that function there are only a two Objects:
```
OBSConnector obsSocket
Controller nanoController
```
So either one of those is not setup properly.
The nanoKontrol should be lighting up just before the program crashes, correct? That eliminates one potential source.

If that is the case, there should be a problem with the connection to the [obs-websocket](https://github.com/Palakis/obs-websocket), which you have to install if you want to use this program at all. Are you able to connect to that through other methods (such as http://t2t2.github.io/obs-tablet-remote/ )?

**Comment by C9Glax** [comment]
No answer, closed
